Region: us-east-2
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-006d5a0f2822b951f
  Ssh:
    KeyName: slurm
  Iam:
    S3Access:
      - BucketName: dvcx-datacomp-small
      - BucketName: dvcx-datacomp-medium
      - BucketName: dvcx-datacomp-large
      - BucketName: dvcx-datacomp-sandbox-small
      - BucketName: dvcx-datacomp-sandbox-workspace
        EnableWriteAccess: true
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
  - Name: queue1
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://dvcx-datacomp-sandbox-workspace/init_env.sh
    Iam:
      S3Access:
        - BucketName: dvcx-datacomp-small
        - BucketName: dvcx-datacomp-medium
        - BucketName: dvcx-datacomp-large
        - BucketName: dvcx-datacomp-sandbox-small
        - BucketName: dvcx-datacomp-sandbox-workspace
          EnableWriteAccess: true
    ComputeResources:
    - Name: p32xlarge
      Instances:
      - InstanceType: p3.2xlarge
      MinCount: 0
      MaxCount: 8
    - Name: p316xlarge
      Instances:
      - InstanceType: p3.16xlarge
      MinCount: 0
      MaxCount: 1
    - Name: g5xlarge
      Instances:
      - InstanceType: g5.xlarge
      MinCount: 0
      MaxCount: 24
    - Name: g4dnxlarge
      Instances:
      - InstanceType: g4dn.xlarge
      MinCount: 0
      MaxCount: 48
    Networking:
      SubnetIds:
      - subnet-006d5a0f2822b951f
SharedStorage:
  - MountDir: /mnt/efs
    Name: share
    StorageType: Efs
    EfsSettings:
      DeletionPolicy: Retain
