input_path: /mnt/efs/dvcx-datacomp-sandbox-small
filter_path: filter.npy
shards_path: /mnt/efs/subset/shards
train_path: train
eval_data_path: /mnt/efs/eval_dataset
eval_out_path: eval
filter_args:
  name: clip_score
  arch: l14
  fraction: 0.3
slurm_train_args:
  nodes: 8
  ntasks-per-node: 1
  cpus-per-task: 1
  constraint: g4dn.xlarge
slurm_evaluate_args:
  nodes: 1
  ntasks: 1
  cpus-per-task: 4
  gpus: 1
  constraint: g4dn.xlarge